### ISSUE TITLE
Error line number confusing

### ISSUE THREAD

**Issue by nygrenh** [rage/python-editor#168]

**Comment by ihantola** [comment]
![CED44EF6-D1A6-418B-9DA4-633020DF40F6](https://user-images.githubusercontent.com/157458/111211037-9e48d180-85d6-11eb-8344-676fd996164c.jpeg)

**Comment by ihantola** [comment]
The feedback of in the very first exercises of cs1 is cryptic and refers to wrap_execution function. The filenames are also unnecessary. In the attached image, the only relevant information is “line 5”.

**Comment by jolampi** [comment]
Parsing of only relevant information sounds reasonable. One thing of note however, different kinds of errors may lead to different errors.

**Comment by jolampi** [comment]
Example of a compile error: `print(":)` produces the following:

```
Error: Traceback (most recent call last):
  File "/lib/python3.8/site-packages/pyodide/_base.py", line 68, in eval_code
    eval(compile(mod, "<exec>", mode="exec"), ns, ns)
  File "<exec>", line 29, in <module>
  File "/lib/python3.8/ast.py", line 45, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    print(":)
            ^
SyntaxError: EOL while scanning string literal
```

**Comment by ihantola** [comment]
Compiler errors are different and could/should be checked first for all inline editor exercises - the feedback could even be the same what any smart editor would give even before executing the code

**Comment by jolampi** [comment]
Showing compile errors on lines they appear on do sound like a valuable feature. I will look into the react-monaco-editor and see how that should be achieved. However, to catch any errors the code needs to be parsed with Pyodide. If done continuously, it may prove out to be be too much for some people's browsers to handle.
